base_link:
  gps0/gps_base_link:
    x: -1.225
    y: 0.0
    z: -0.11
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gps1/gps_base_link:
    x: -1.000
    y: 0.0
    z: 1.28
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_base_link:
    x: -0.420
    y: 0.0
    z: -1.180
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  cl_base_link:
    x: 0.2
    y: 0.0
    z: -0.11
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
