sensor_kit_base_link:
  gps0/gps_link:
    x: 0.0
    y: 0.0
    z: 1.17
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gps1/gps_link:
    x: 0.225
    y: 0.0
    z: 1.28
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: 0.805
    y: 0.0
    z: 0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lidar_link:
    x: 1.225
    y: 0.0
    z: 1.28
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  cl_link:
    x: 1.425
    y: 0.0
    z: 1.17
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
